### PR TITLE
Add Debian bookworm support

### PR DESCRIPTION
**Pull request by lbetz**

### CODE REVIEW

**Review by smortex — APPROVED** [review]
Fine, but when adding support for new systems, we do minor version bumps (i.e. *add functionality in a backward compatible manner*) rather than a patch version bump (i.e. *backward compatible bug fixes*).

**Comment by lbetz** [comment]
Wasn't new, Debian bookworm support added in 5.0.0. But forgot to add metadata file.

**Comment by smortex** [comment]
Ah, acceptance tests help to spot this :wink: 

Maybe we can start with a very basic one like this:
```ruby
# frozen_string_literal: true

require 'spec_helper_acceptance'

describe 'incinga class' do
  it 'works idempotently with no errors' do
    pp = <<~MANIFEST
      class { 'incinga':
      }
    MANIFEST

    apply_manifest(pp, catch_failures: true)
    apply_manifest(pp, catch_changes: true)
  end
end
```

**Comment by lbetz** [comment]
Fundamentally correct, we should do that. I removed the old vagrant base acceptence test before moving to voxpupuli. But it's not quite that simple. This module primarily provides helper classes, such as icinga::repos for the three other Icinga modules or icinga::redis for the icingadb module. The main class icinga inside this module is also an private class used by icinga::agent, icinga::worker and icinga::server. All three of these are wrapper classes of the icinga2 class of module icinga2 and so on.

**Pull request merged**
